title: "Gallexy urban Data Intelligence Institute"
description: "Independent nonprofit research initiative"
remote_theme: pages-themes/minimal@v0.2.0
# 配置导航栏菜单
header_pages:
  - about.md
  - research.md
  - contact.md
