title: "Gallexy urban Data Intelligence Institute"
description: "Independent nonprofit research initiative"
theme: jekyll-theme-modernist
# 配置导航栏菜单
header_pages:
  - about.md
  - research.md
  - contact.md
